### ISSUE TITLE
mapimageengine not working for 4.0.0

### ISSUE THREAD

**Issue by SuperAdam47** [genboy/pocketmineplugins#35]

**Comment by SuperAdam47** [comment]
@genboy

**Comment by genboy** [comment]
Thank you, I noticed that too. 
https://poggit.pmmp.io/p/MapImageEngine/1.1.1 is the latest, all I did was bump the version.
What pmmp version do you use?
Is an error reported or it just doesn't work?

**Comment by SuperAdam47** [comment]
you will encounter a lot of mistakes when you start correcting.

**Comment by SuperAdam47** [comment]
not working for Altay 4.0.0

**Comment by genboy** [comment]
@SuperAdam47 i will close this soon as i can not fix the error, only see when a new version can be tested and added to the repo

**Comment by SuperAdam47** [comment]
help?
https://github.com/SuperAdam47/MapImageEngine

**Comment by SuperAdam47** [comment]
I made some fixes
