### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by ItsMax123** [genboy/pocketmineplugins#45]
Ok so I have recently realized that people can do commands with spaces to evade the combat logger, so, since this is probably a problem for multiple servers, you should probably make a plugin to prevent it (Or just make ur own combat logger with it implemented).

Thank you so much in advanced, even if you decline this its great of you just to read these and to do what you do for the community!

**Comment by genboy** [comment]
Allthough this might be a brilliant idea, i probably will not make a combat logger or a while, sorry.
